# meta_cell_types.R
# Returns a named list of meta-type buckets -> character vectors of cell types

define_meta_cell_types <- function() {
  meta_types <- list(
    # Neuron cell types
    neurons = c(
      "CNS interneuron",
      "GABAergic interneuron",
      "GABAergic neuron",
      "L2/3 intratelencephalic projecting glutamatergic neuron",
      "L2/3-6 intratelencephalic projecting glutamatergic neuron",
      "L4 intratelencephalic projecting glutamatergic neuron",
      "L5 extratelencephalic projecting glutamatergic cortical neuron",
      "L5/6 near-projecting glutamatergic neuron",
      "L5/6 near-projecting glutamatergic neuron of the primary motor cortex",
      "L6 corticothalamic-projecting glutamatergic cortical neuron",
      "L6 intratelencephalic projecting glutamatergic neuron of the primary motor cortex",
      "L6b glutamatergic cortical neuron",
      "VIP GABAergic cortical interneuron",
      "bipolar neuron",
      "brainstem motor neuron",
      "cardiac neuron",
      "caudal ganglionic eminence derived interneuron",
      "central nervous system neuron",
      "cerebellar neuron",
      "cerebellum glutamatergic neuron",
      "cerebral cortex GABAergic interneuron",
      "cerebral cortex neuron",
      "cerebral cortex pyramidal neuron",
      "chandelier pvalb GABAergic cortical interneuron",
      "cortical interneuron",
      "corticothalamic-projecting glutamatergic cortical neuron",
      "direct pathway medium spiny neuron",
      "dopaminergic neuron",
      "enteric neuron",
      "extratelencephalic-projecting glutamatergic cortical neuron",
      "forebrain neuroblast",
      "ganglion interneuron",
      "glutamatergic neuron",
      "hippocampal interneuron",
      "hippocampal pyramidal neuron",
      "indirect pathway medium spiny neuron",
      "inhibitory interneuron",
      "inhibitory motor neuron",
      "interneuron",
      "lamp5 GABAergic cortical interneuron",
      "medial ganglionic eminence derived GABAergic cortical interneuron",
      "medium spiny neuron",
      "midbrain dopaminergic neuron",
      "motor neuron",
      "near-projecting glutamatergic cortical neuron",
      "neural cell",
      "neural progenitor cell",
      "neural stem cell",
      "neuroblast (sensu Nematoda and Protostomia)",
      "neuroblast (sensu Vertebrata)",
      "neuron",
      "neuron associated cell",
      "neuron associated cell (sensu Vertebrata)",
      "neuron of the forebrain",
      "neuronal brush cell",
      "neuronal receptor cell",
      "peripheral nervous system neuron",
      "primary sensory neuron (sensu Teleostei)",
      "pyramidal neuron",
      "retinal bipolar neuron",
      "retinal progenitor cell",
      "sensory neuron",
      "sncg GABAergic cortical interneuron",
      "sst GABAergic cortical interneuron",
      "sst chodl GABAergic cortical interneuron",
      "stellate neuron",
      "sympathetic neuron",
      "visceromotor neuron"
    ),

    # Immune cell types
    immune = c(
      "B cell",
      "T cell",
      "plasma cell",
      "memory B cell",
      "naive B cell",
      "IgA plasma cell",
      "IgG plasma cell",
      "IgM plasma cell",
      "germinal center B cell",
      "follicular B cell",
      "class switched memory B cell",
      "unswitched memory B cell",
      "immature B cell",
      "mature B cell",
      "precursor B cell",
      "pro-B cell",
      "plasmablast",
      "CD4-positive, alpha-beta T cell",
      "CD8-positive, alpha-beta T cell",
      "regulatory T cell",
      "gamma-delta T cell",
      "naive T cell",
      "memory T cell",
      "effector memory CD4-positive, alpha-beta T cell",
      "effector memory CD8-positive, alpha-beta T cell",
      "effector memory CD8-positive, alpha-beta T cell, terminally differentiated",
      "activated CD4-positive, alpha-beta T cell",
      "activated CD4-positive, alpha-beta T cell, human",
      "activated CD8-positive, alpha-beta T cell",
      "CD4-positive helper T cell",
      "CD4-positive, alpha-beta memory T cell",
      "CD8-positive, alpha-beta memory T cell",
      "CD8-positive, alpha-beta memory T cell, CD45RO-positive",
      "CD8-positive, alpha-beta cytotoxic T cell",
      "CD4-positive, alpha-beta cytotoxic T cell",
      "CD4-positive, CD25-positive, alpha-beta regulatory T cell",
      "CD4-positive, alpha-beta thymocyte",
      "CD8-positive, alpha-beta thymocyte",
      "CD8-alpha alpha positive, gamma-delta intraepithelial T cell",
      "CD8-alpha-beta-positive, alpha-beta intraepithelial T cell",
      "naive thymus-derived CD4-positive, alpha-beta T cell",
      "naive thymus-derived CD8-positive, alpha-beta T cell",
      "T follicular helper cell",
      "T-helper 1 cell",
      "T-helper 17 cell",
      "effector CD4-positive, alpha-beta T cell",
      "helper T cell",
      "cytotoxic T cell",
      "alpha-beta T cell",
      "mature alpha-beta T cell",
      "immature alpha-beta T cell",
      "mature gamma-delta T cell",
      "natural T-regulatory cell",
      "lung resident memory CD4-positive, alpha-beta T cell",
      "lung resident memory CD8-positive, alpha-beta T cell",
      "intraepithelial lymphocyte",
      "natural killer cell",
      "CD16-negative, CD56-bright natural killer cell, human",
      "CD16-positive, CD56-dim natural killer cell, human",
      "mature NK T cell",
      "activated type II NK T cell",
      "decidual natural killer cell, human",
      "innate lymphoid cell",
      "group 3 innate lymphoid cell",
      "group 3 innate lymphoid cell, human",
      "immature innate lymphoid cell",
      "mucosal invariant T cell",
      "macrophage",
      "alveolar macrophage",
      "alternatively activated macrophage",
      "tissue-resident macrophage",
      "inflammatory macrophage",
      "lung macrophage",
      "lung interstitial macrophage",
      "colon macrophage",
      "Kupffer cell",
      "Hofbauer cell",
      "elicited macrophage",
      "kidney interstitial alternatively activated macrophage",
      "kidney resident macrophage",
      "metallothionein-positive alveolar macrophage",
      "monocyte",
      "classical monocyte",
      "non-classical monocyte",
      "intermediate monocyte",
      "CD14-positive monocyte",
      "CD14-positive, CD16-positive monocyte",
      "CD14-positive, CD16-negative classical monocyte",
      "MHC-II-positive classical monocyte",
      "dendritic cell",
      "conventional dendritic cell",
      "plasmacytoid dendritic cell",
      "plasmacytoid dendritic cell, human",
      "myeloid dendritic cell",
      "myeloid dendritic cell, human",
      "CD1c-positive myeloid dendritic cell",
      "mature conventional dendritic cell",
      "monocyte-derived dendritic cell",
      "dendritic cell, human",
      "liver dendritic cell",
      "neutrophil",
      "basophil",
      "eosinophil",
      "mast cell",
      "granulocyte",
      "Langerhans cell",
      "epidermal Langerhans cell",
      "lymphocyte",
      "leukocyte",
      "myeloid cell",
      "myeloid leukocyte",
      "mononuclear phagocyte",
      "mononuclear cell",
      "professional antigen presenting cell",
      "hematopoietic cell",
      "hematopoietic precursor cell",
      "hematopoietic stem cell",
      "cord blood hematopoietic stem cell",
      "lymphoid lineage restricted progenitor cell"
    ),

    # Epithelial barrier cells
    epithelial_barrier = c(
      "epithelial cell",
      "enterocyte",
      "goblet cell",
      "intestinal epithelial cell",
      "basal cell",
      "columnar/cuboidal epithelial cell",
      "squamous epithelial cell",
      "M cell of gut",
      "tuft cell of colon",
      "tuft cell of small intestine",
      "intestinal tuft cell",
      "paneth cell",
      "paneth cell of colon",
      "paneth cell of epithelium of small intestine",
      "BEST4+ intestinal epithelial cell, human",
      "epithelial cell of stomach",
      "epithelial cell of esophagus",
      "epithelial cell of lung",
      "epithelial cell of lower respiratory tract",
      "epithelial cell of alveolus of lung",
      "epithelial cell of small intestine",
      "epithelial cell of proximal tubule",
      "epithelial cell of proximal tubule segment 1",
      "epithelial cell of proximal tubule segment 3",
      "epithelial cell of exocrine pancreas",
      "epithelial cell of pancreas",
      "epithelial cell of stratum germinativum of esophagus",
      "epithelial cell of sweat gland",
      "colon epithelial cell",
      "colon goblet cell",
      "intestine goblet cell",
      "small intestine goblet cell",
      "large intestine goblet cell",
      "ileal goblet cell",
      "lung goblet cell",
      "bronchial goblet cell",
      "respiratory goblet cell",
      "tracheobronchial goblet cell",
      "nasal mucosa goblet cell",
      "enterocyte of colon",
      "enterocyte of epithelium of large intestine",
      "enterocyte of epithelium of small intestine",
      "enterocyte of epithelium proper of duodenum",
      "enterocyte of epithelium proper of ileum",
      "enterocyte of epithelium proper of jejunum",
      "enterocyte of epithelium proper of small intestine",
      "absorptive cell",
      "intestinal crypt stem cell",
      "intestinal crypt stem cell of colon",
      "intestinal crypt stem cell of small intestine",
      "transit amplifying cell",
      "transit amplifying cell of colon",
      "transit amplifying cell of small intestine",
      "bronchial epithelial cell",
      "airway epithelial cell",
      "alveolar epithelial cell",
      "pulmonary alveolar type 1 cell",
      "pulmonary alveolar type 2 cell",
      "pulmonary alveolar epithelial cell",
      "ciliated cell",
      "ciliated columnar cell of tracheobronchial tree",
      "lung ciliated cell",
      "multi-ciliated epithelial cell",
      "club cell",
      "basal cell of epidermis",
      "basal cell of epithelium of lobular bronchiole",
      "respiratory basal cell",
      "airway submucosal gland duct basal cell",
      "keratinocyte",
      "hair follicular keratinocyte",
      "suprabasal keratinocyte",
      "urothelial cell",
      "bladder urothelial cell",
      "kidney pelvis urothelial cell",
      "melanocyte",
      "melanocyte of skin",
      "hepatocyte",
      "centrilobular region hepatocyte",
      "midzonal region hepatocyte",
      "periportal region hepatocyte",
      "cholangiocyte",
      "intrahepatic cholangiocyte",
      "kidney epithelial cell",
      "kidney collecting duct cell",
      "kidney collecting duct intercalated cell",
      "kidney collecting duct principal cell",
      "kidney connecting tubule epithelial cell",
      "kidney connecting tubule principal cell",
      "kidney cortex collecting duct epithelial cell",
      "kidney distal convoluted tubule epithelial cell",
      "kidney loop of Henle epithelial cell",
      "kidney loop of Henle ascending limb epithelial cell",
      "kidney loop of Henle cortical thick ascending limb epithelial cell",
      "kidney loop of Henle descending limb epithelial cell",
      "kidney loop of Henle thick ascending limb epithelial cell",
      "kidney loop of Henle thin ascending limb epithelial cell",
      "kidney loop of Henle thin descending limb epithelial cell",
      "renal intercalated cell",
      "renal alpha-intercalated cell",
      "renal beta-intercalated cell",
      "renal principal cell",
      "papillary tips cell",
      "parietal epithelial cell",
      "podocyte",
      "brush cell",
      "brush cell of tracheobronchial tree",
      "respiratory epithelial cell",
      "stratified epithelial cell",
      "glandular epithelial cell",
      "ionocyte",
      "pulmonary ionocyte",
      "microfold cell of epithelium of small intestine",
      "airway submucosal gland collecting duct epithelial cell",
      "fallopian tube secretory epithelial cell",
      "pancreatic ductal cell"
    ),

    # Vascular and endothelial cells
    endothelial_vascular = c(
      "endothelial cell",
      "capillary endothelial cell",
      "vein endothelial cell",
      "endothelial cell of artery",
      "endothelial cell of lymphatic vessel",
      "blood vessel endothelial cell",
      "cardiac endothelial cell",
      "cardiac blood vessel endothelial cell",
      "endocardial cell",
      "glomerular endothelial cell",
      "glomerular capillary endothelial cell",
      "lung endothelial cell",
      "lung microvascular endothelial cell",
      "pulmonary artery endothelial cell",
      "pulmonary capillary endothelial cell",
      "endothelial cell of hepatic sinusoid",
      "endothelial cell of pericentral hepatic sinusoid",
      "endothelial cell of periportal hepatic sinusoid",
      "endothelial cell of vascular tree",
      "endothelial cell of arteriole",
      "endothelial cell of venule",
      "endothelial stalk cell",
      "endothelial cell of placenta",
      "endothelial cell of respiratory system lymphatic vessel",
      "endothelial cell of uterus",
      "colon endothelial cell",
      "kidney capillary endothelial cell",
      "alveolar capillary type 1 endothelial cell",
      "alveolar capillary type 2 endothelial cell",
      "vein endothelial cell of respiratory system",
      "pericyte",
      "lung pericyte",
      "renal interstitial pericyte",
      "perivascular cell",
      "smooth muscle cell",
      "vascular associated smooth muscle cell",
      "blood vessel smooth muscle cell",
      "bronchial smooth muscle cell",
      "bronchiolar smooth muscle cell",
      "tracheobronchial smooth muscle cell",
      "smooth muscle cell of the pulmonary artery",
      "microcirculation associated smooth muscle cell",
      "enteric smooth muscle cell",
      "smooth muscle fiber of ileum",
      "cardiac muscle cell",
      "regular atrial cardiac myocyte",
      "regular ventricular cardiac myocyte",
      "ventricular cardiac muscle cell",
      "uterine smooth muscle cell",
      "smooth muscle myoblast",
      "cardiac muscle myoblast",
      "vasa recta ascending limb cell",
      "vasa recta descending limb cell"
    ),

    # Secretory and endocrine cells
    secretory_endocrine = c(
      "enteroendocrine cell",
      "endocrine cell",
      "neuroendocrine cell",
      "enteroendocrine cell of colon",
      "enteroendocrine cell of small intestine",
      "intestinal enteroendocrine cell",
      "type EC enteroendocrine cell",
      "type L enteroendocrine cell",
      "type D enteroendocrine cell",
      "type G enteroendocrine cell",
      "type A enteroendocrine cell",
      "type I enteroendocrine cell",
      "type N enteroendocrine cell",
      "P/D1 enteroendocrine cell",
      "GIP cell",
      "pancreatic A cell",
      "type B pancreatic cell",
      "pancreatic D cell",
      "pancreatic PP cell",
      "PP cell",
      "pancreatic epsilon cell",
      "pancreatic endocrine cell",
      "pancreatic acinar cell",
      "acinar cell",
      "chief cell",
      "parietal cell",
      "peptic cell",
      "mucous cell of stomach",
      "mucous neck cell",
      "foveolar cell of stomach",
      "enterochromaffin-like cell",
      "secretory cell",
      "serous cell of epithelium of bronchus",
      "serous cell of epithelium of lobular bronchiole",
      "serous secreting cell",
      "serous secreting cell of bronchus submucosal gland",
      "tracheobronchial serous cell",
      "mucus secreting cell",
      "mucus secreting cell of bronchus submucosal gland",
      "mucus secreting cell of tracheobronchial tree submucosal gland",
      "lung secretory cell",
      "lung neuroendocrine cell",
      "salivary gland glandular cell",
      "glandular cell of esophagus",
      "sebaceous gland cell",
      "sebum secreting cell"
    ),

    # Stromal support cells
    stromal_support = c(
      "fibroblast",
      "myofibroblast cell",
      "mesenchymal cell",
      "stromal cell",
      "mesenchymal stem cell",
      "stellate cell",
      "hepatic stellate cell",
      "pancreatic stellate cell",
      "adipocyte",
      "subcutaneous adipocyte",
      "epicardial adipocyte",
      "adipocyte of epicardial fat of left ventricle",
      "chondrocyte",
      "fibroblast of lung",
      "bronchus fibroblast of lung",
      "alveolar adventitial fibroblast",
      "alveolar type 1 fibroblast cell",
      "lung perichondrial fibroblast",
      "pulmonary interstitial fibroblast",
      "fibroblast of cardiac tissue",
      "skin fibroblast",
      "muscle fibroblast",
      "kidney interstitial fibroblast",
      "mesothelial fibroblast",
      "embryonic fibroblast",
      "secondary crest myofibroblast",
      "adventitial cell",
      "collagen secreting cell",
      "muscle cell",
      "skeletal muscle fiber",
      "skeletal muscle satellite cell",
      "cell of skeletal muscle",
      "fast muscle cell",
      "slow muscle cell",
      "myoepithelial cell",
      "myoepithelial cell of bronchus submucosal gland",
      "mural cell",
      "mesangial cell",
      "kidney interstitial cell",
      "mesothelial cell",
      "mesothelial cell of epicardium",
      "mesothelial cell of pleura",
      "contractile cell",
      "interstitial cell of Cajal",
      "Leydig cell",
      "peritubular myoid cell",
      "reticular cell",
      "decidual cell"
    ),

    # Glial support cells
    glial_support = c(
      "glial cell",
      "Schwann cell",
      "myelinating Schwann cell",
      "non-myelinating Schwann cell",
      "enteroglial cell"
    )
  )
  return(meta_types)
}